FROM alpine:latest
RUN apk add --no-cache vim nodejs npm

RUN npm install -g intelephense
RUN npm install -g @vue/language-server@2.2.10
RUN npm install -g typescript@5.8.3
RUN npm install -g vim-language-server
RUN npm install -g typescript-language-server

WORKDIR /app
VOLUME /app
