FROM alpine:latest
RUN apk add --no-cache vim nodejs npm

RUN npm install -g intelephense
RUN npm install -g @vue/language-server@2.2.10
RUN npm install -g typescript@5.8.3

WORKDIR /app
VOLUME /app
CMD ["vim", "-u", "DEFAULTS", "-c", "source /app/plugin/lsp.vim", "-c", "source /app/tests/run.vim"]
